version: '3.8'

services:
  app:
    container_name: go-gin-todo-api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - go-cache:/go
    environment:
      - GO_ENV=development
    command: air
    restarts: unless-stopped

volumes:
  go-cache:
