services:
  # api:
  #   container_name: go-gin-todo-api
  #   build: .
  #   ports:
  #     - '8080:8080'
  #   environment:
  #     - SERVER_PORT=8080
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - DB_USER=postgres
  #     - DB_PASSWORD=password
  #     - DB_NAME=todo_db
  #     - DB_SSLMODE=disable
  #     - JWT_SECRET=change-me
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   restart: unless-stopped
  db:
    container_name: go-postgres
    image: postgres:15-alpine
    ports:
      - '55432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d todo_db']
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_data:
