@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRlc3R1c2VyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzYwNjg3OTIwLCJpYXQiOjE3NjA2MDE1MjB9.O8eZPQlj-LJQij_6Xxe8s0q5VYW-eVm7xlyhhbzT1KQ
@TASK_ID=2
###
GET http://localhost:8080/health

###  Task APIs
GET http://localhost:8080/api/v1/tasks
Authorization: Bearer {{TOKEN}}

###
POST http://localhost:8080/api/v1/tasks
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "title": "New Task 111",
    "description": "This is a new task 1111"
}

###
GET http://localhost:8080/api/v1/tasks/{{TASK_ID}}
Authorization: Bearer {{TOKEN}}

### Update Task
PATCH http://localhost:8080/api/v1/tasks/{{TASK_ID}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "title": "Updated Task 111",
    "description": "Updated description 1111",
    "completed": true
}